== Introduction ==

Once upon a time, the World Wide Web was created as a way to share
scientific research by way of documents linked together across the Internet.
But, that was a time when scientists and academics were main groups
using the net—so of course sharing research was one of the hottest things
around. But, as more of the world's people have come online, we've expanded
the web into a more broadly social medium through which we can share the
details and events of our lives with one another.

From formal papers, to daily missives, to hourly and even up-to-the minute
status updates complete with rich multimedia and sensor data—we've moved
from standalone documents to fluid streams. The pace is quickening, and the
power of expression grows. And yet, the best of it still looks like a World
Wide Web: as hyperlinked and interconnected as our thoughts and
relationships to each other.

Apropos of all the above, *Activity Streams* is a term used to describe
these rivers of information and experience flowing on the web. And, as you
can tell from the title, that's topic of this book. More to the point, this
is a book that intends to help you to explore concepts and technologies
that drive *Activity Streams* and experiment with them in practical and
interesting ways.

=== What's in this book? ===

Through roughly equal parts code and prose and an occasional illustrative
figure, this book will aim to provide you with practical tools and
understanding to apply toward *Activity Streams*. As the title should
imply, this is a book for _tinkering_, intended for hackers and makers.
Clarity and tweakability will feature more heavily than efficiency or
completeness. There will be loose ends and exercises left to the reader.
And, above all, this book is about getting you hands on with the subject.

=== Who is this book for? ===

As a book built toward tinkering, it will not cover basic programming. You
should already be comfortable with editing source files and building
applications in at least one or more languages—particularly JavaScript and
Python. You'll also be well-served by having at least a basic grasp of web
technologies such as HTTP, HTML, XML, and JSON.

That said, efforts will be made to explain the essentials and the most
significant parts of the technologies used throughout the book. You'll also
find pointers leading to more information and further experiments for
exploration.

This will also be a very Unix-centric book in its examples. In other words,
if you are most comfortable in a Windows environment, you might find some
parts more difficult to follow than if you were a Linux or Mac OS X
user.

And, finally, it will be helpful to have some form of web hosting
available. For the most part, this book won't require anything like an
expensive dedicated or colocated server. But, occasionally, a server out
on the public Internet will come in handy. In most cases, the examples
herein should be useful with inexpensive—or even free—services, and
alternatives will be offered where appropriate.

=== How's this book structured? ===

TBD

=== Conventions used in this book ===

TBD

=== Source Code ===

Both the source code for this book and all the example programs are
available here:

    http://github.com/lmorchard/tinkering-with-activity-streams/

// vim: set syntax=asciidoc smartindent formatoptions=tcn textwidth=75:
